#!/bin/bash

# JAVA
apt-add-repository -y ppa:webupd8team/java
# Update
apt-get update && apt-get install -y debconf-utils
# TRICK TO SET LICENSE FOR JAVA INSTALL
echo debconf shared/accepted-oracle-license-v1-1 select true | debconf-set-selections
echo debconf shared/accepted-oracle-license-v1-1 seen true | debconf-set-selections
# INSTALL JAVA
apt-get install -y oracle-java8-installer
apt-get install -y oracle-java8-set-default
# SET JAVA ENVIRONMENT
echo "JAVA_HOME=/usr/lib/jvm/java-8-oracle" >> "/etc/environment"
