#!/bin/bash

wget http://downloads.ghostscript.com/public/binaries/ghostscript-9.15-linux-x86_64.tgz -P /opt
tar -C /opt -xzvf /opt/ghostscript-9.15-linux-x86_64.tgz
mv /usr/bin/gs /usr/bin/gs--
ln -s /opt/ghostscript-9.15-linux-x86_64/gs-915-linux_x86_64 /usr/bin/gs
