#!/bin/bash

wget http://owl.phy.queensu.ca/~phil/exiftool/Image-ExifTool-10.17.tar.gz -P /tmp
tar -C /tmp -xzvf /tmp/Image-ExifTool-10.17.tar.gz
cd /tmp/Image-ExifTool-10.17 && perl Makefile.PL && make test && make install
